### ISSUE TITLE
Test CAN communication

### ISSUE THREAD

**Issue by jetkov** [uwrobotics/MarsRover2019-firmware#4]
We need to make sure that CAN is working physically as well as with the MBED library (or another external library).

**Comment by jetkov** [comment]
Use the CANable first: 
https://canable.io/getting-started.html

**Comment by f-jiang** [comment]
Tested CAN on safety board and ran the `test_can` app and was able to communicate over the bus using my laptop as well as observe CAN bus traffic. Did all of this by following the appropriate instructions in the [Google doc](https://docs.google.com/document/d/1W2ZsdWrA3AtyNjVqybUnyc1IjGI5klCLwZGarSxkh5o/edit). Next step is to try the MBED library.

**Comment by f-jiang** [comment]
Able to send and receive CAN messages using MBED on Science, Arm, and Safety boards when connected to either laptop or Jetson. Used `test_can` like before.

**Comment by jetkov** [comment]
Sweet!
