### ISSUE TITLE
Test reading PWM encoder input

### ISSUE THREAD

**Issue by jetkov** [uwrobotics/MarsRover2019-firmware#6]

**Comment by f-jiang** [comment]
Tested the AMT102 and AMT103 digital encoders ([datasheet here](https://www.cui.com/product/resource/amt10.pdf)) on the science board using an updated `test_qei` that can be found on branch `feilan/misc-testing`

**Comment by jetkov** [comment]
Tested reading the PWM signal from the [MAE3](https://www.usdigital.com/products/mae3) absolute encoders on the arm board. Tested with `test_pwmin` app in `alex/improvePWMTesting`, was able to read with decent (2 or 3 decimal places stable) precision on ENC_A1 and ENC_A2, however was not able to get any signal input from ENC_A3 connection.
